[package]
name = "paneless"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
windows = { version = "0.58.0", features = ["Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_System_SystemServices", "Win32_UI_WindowsAndMessaging"] }
